# config/pea_stocks.py

PEA_UNIVERSE = [
    # --- FRANCE : CAC 40 (40) ---
    {"ticker": "AC.PA", "nom": "Accor", "sector": "Hôtellerie"},
    {"ticker": "AI.PA", "nom": "Air Liquide", "sector": "Industrie"},
    {"ticker": "AIR.PA", "nom": "Airbus", "sector": "Aéronautique"},
    {"ticker": "MT.AS", "nom": "ArcelorMittal", "sector": "Acier"},
    {"ticker": "CS.PA", "nom": "AXA", "sector": "Assurance"},
    {"ticker": "BNP.PA", "nom": "BNP Paribas", "sector": "Banque"},
    {"ticker": "EN.PA", "nom": "Eiffage", "sector": "BTP"},
    {"ticker": "EL.PA", "nom": "EssilorLuxottica", "sector": "Santé"},
    {"ticker": "STLAP.PA", "nom": "Stellantis", "sector": "Automobile"},
    {"ticker": "CA.PA", "nom": "Carrefour", "sector": "Distribution"},
    {"ticker": "ACA.PA", "nom": "Crédit Agricole", "sector": "Banque"},
    {"ticker": "BN.PA", "nom": "Danone", "sector": "Consommation"},
    {"ticker": "DSY.PA", "nom": "Dassault Systèmes", "sector": "Technologie"},
    {"ticker": "ENGI.PA", "nom": "Engie", "sector": "Énergie"},
    {"ticker": "ERF.PA", "nom": "Eurofins Scientific", "sector": "Santé"},
    {"ticker": "RMS.PA", "nom": "Hermès", "sector": "Luxe"},
    {"ticker": "KER.PA", "nom": "Kering", "sector": "Luxe"},
    {"ticker": "LR.PA", "nom": "Legrand", "sector": "Industrie"},
    {"ticker": "OR.PA", "nom": "L'Oréal", "sector": "Consommation"},
    {"ticker": "MC.PA", "nom": "LVMH", "sector": "Luxe"},
    {"ticker": "ML.PA", "nom": "Michelin", "sector": "Automobile"},
    {"ticker": "ORA.PA", "nom": "Orange", "sector": "Télécoms"},
    {"ticker": "RI.PA", "nom": "Pernod Ricard", "sector": "Consommation"},
    {"ticker": "PUB.PA", "nom": "Publicis", "sector": "Médias"},
    {"ticker": "RNO.PA", "nom": "Renault", "sector": "Automobile"},
    {"ticker": "SAF.PA", "nom": "Safran", "sector": "Aéronautique"},
    {"ticker": "SGO.PA", "nom": "Saint-Gobain", "sector": "BTP"},
    {"ticker": "SAN.PA", "nom": "Sanofi", "sector": "Santé"},
    {"ticker": "SU.PA", "nom": "Schneider Electric", "sector": "Industrie"},
    {"ticker": "GLE.PA", "nom": "Société Générale", "sector": "Banque"},
    {"ticker": "STMPA.PA", "nom": "STMicroelectronics", "sector": "Technologie"},
    {"ticker": "HO.PA", "nom": "Thales", "sector": "Défense"},
    {"ticker": "TTE.PA", "nom": "TotalEnergies", "sector": "Énergie"},
    {"ticker": "URW.PA", "nom": "Unibail-Rodamco", "sector": "Immobilier"},
    {"ticker": "VIE.PA", "nom": "Veolia", "sector": "Services"},
    {"ticker": "DG.PA", "nom": "Vinci", "sector": "BTP"},
    {"ticker": "VIV.PA", "nom": "Vivendi", "sector": "Médias"},
    {"ticker": "WLN.PA", "nom": "Worldline", "sector": "Technologie"},

    # --- FRANCE : SBF 120 / MID CAPS (SÉLECTION) ---
    {"ticker": "ATE.PA", "nom": "Alten", "sector": "Technologie"},
    {"ticker": "AMUN.PA", "nom": "Amundi", "sector": "Finance"},
    {"ticker": "AKE.PA", "nom": "Arkema", "sector": "Chimie"},
    {"ticker": "ATO.PA", "nom": "Atos", "sector": "Technologie"},
    {"ticker": "BIM.PA", "nom": "BioMérieux", "sector": "Santé"},
    {"ticker": "BOL.PA", "nom": "Bolloré", "sector": "Holding"},
    {"ticker": "BOUY.PA", "nom": "Bouygues", "sector": "BTP"},
    {"ticker": "CAP.PA", "nom": "Capgemini", "sector": "Technologie"},
    {"ticker": "COFA.PA", "nom": "Coface", "sector": "Finance"},
    {"ticker": "COV.PA", "nom": "Covivio", "sector": "Immobilier"},
    {"ticker": "DEC.PA", "nom": "JCDecaux", "sector": "Médias"},
    {"ticker": "DIM.PA", "nom": "Sartorius Stedim", "sector": "Santé"},
    {"ticker": "EDEN.PA", "nom": "Edenred", "sector": "Services"},
    {"ticker": "EMEIS.PA", "nom": "Emeis", "sector": "Santé"},
    {"ticker": "ERA.PA", "nom": "Eramet", "sector": "Mines"},
    {"ticker": "FDJ.PA", "nom": "Française des Jeux", "sector": "Loisirs"},
    {"ticker": "GFC.PA", "nom": "Gecina", "sector": "Immobilier"},
    {"ticker": "GET.PA", "nom": "Getlink", "sector": "Transport"},
    {"ticker": "ICAD.PA", "nom": "Icade", "sector": "Immobilier"},
    {"ticker": "IDL.PA", "nom": "ID Logistics", "sector": "Transport"},
    {"ticker": "IPS.PA", "nom": "Ipsen", "sector": "Santé"},
    {"ticker": "ITP.PA", "nom": "Interparfums", "sector": "Consommation"},
    {"ticker": "LI.PA", "nom": "Klepierre", "sector": "Immobilier"},
    {"ticker": "LNA.PA", "nom": "LNA Santé", "sector": "Santé"},
    {"ticker": "MF.PA", "nom": "Wendel", "sector": "Holding"},
    {"ticker": "MERY.PA", "nom": "Mercialys", "sector": "Immobilier"},
    {"ticker": "MMT.PA", "nom": "M6", "sector": "Médias"},
    {"ticker": "NEX.PA", "nom": "Nexans", "sector": "Industrie"},
    {"ticker": "NXI.PA", "nom": "Nexity", "sector": "Immobilier"},
    {"ticker": "OVH.PA", "nom": "OVHcloud", "sector": "Technologie"},
    {"ticker": "OPM.PA", "nom": "OP Mobility", "sector": "Automobile"},
    {"ticker": "RCO.PA", "nom": "Rémy Cointreau", "sector": "Consommation"},
    {"ticker": "RUI.PA", "nom": "Rubis", "sector": "Énergie"},
    {"ticker": "SK.PA", "nom": "SEB", "sector": "Consommation"},
    {"ticker": "SCR.PA", "nom": "SCOR", "sector": "Assurance"},
    {"ticker": "SESG.PA", "nom": "SES", "sector": "Télécoms"},
    {"ticker": "SOI.PA", "nom": "Soitec", "sector": "Technologie"},
    {"ticker": "SOP.PA", "nom": "Sopra Steria", "sector": "Technologie"},
    {"ticker": "SPIE.PA", "nom": "Spie", "sector": "Services"},
    {"ticker": "TFI.PA", "nom": "TF1", "sector": "Médias"},
    {"ticker": "UBI.PA", "nom": "Ubisoft", "sector": "Jeux Vidéo"},
    {"ticker": "VK.PA", "nom": "Vallourec", "sector": "Industrie"},
    {"ticker": "VLA.PA", "nom": "Valneva", "sector": "Santé"},
    {"ticker": "VIRP.PA", "nom": "Virbac", "sector": "Santé"},
    {"ticker": "VETO.PA", "nom": "Vetoquinol", "sector": "Santé"},
    {"ticker": "BEN.PA", "nom": "Bénéteau", "sector": "Loisirs"},
    {"ticker": "TRIA.PA", "nom": "Trigano", "sector": "Loisirs"},
    {"ticker": "ALMD.PA", "nom": "Median Tech", "sector": "Santé"},
    {"ticker": "EXO.PA", "nom": "Exel Industries", "sector": "Industrie"},

    # --- ALLEMAGNE (DAX 40 + MDAX) ---
    {"ticker": "ADS.DE", "nom": "Adidas", "sector": "Consommation"},
    {"ticker": "ALV.DE", "nom": "Allianz", "sector": "Assurance"},
    {"ticker": "BAS.DE", "nom": "BASF", "sector": "Chimie"},
    {"ticker": "BAYN.DE", "nom": "Bayer", "sector": "Santé"},
    {"ticker": "BEI.DE", "nom": "Beiersdorf", "sector": "Consommation"},
    {"ticker": "BMW.DE", "nom": "BMW", "sector": "Automobile"},
    {"ticker": "CBK.DE", "nom": "Commerzbank", "sector": "Banque"},
    {"ticker": "CON.DE", "nom": "Continental", "sector": "Automobile"},
    {"ticker": "1COV.DE", "nom": "Covestro", "sector": "Chimie"},
    {"ticker": "DTG.DE", "nom": "Daimler Truck", "sector": "Industrie"},
    {"ticker": "DBK.DE", "nom": "Deutsche Bank", "sector": "Banque"},
    {"ticker": "DB1.DE", "nom": "Deutsche Börse", "sector": "Finance"},
    {"ticker": "DHL.DE", "nom": "DHL Group", "sector": "Logistique"},
    {"ticker": "DTE.DE", "nom": "Deutsche Telekom", "sector": "Télécoms"},
    {"ticker": "EOAN.DE", "nom": "E.ON", "sector": "Énergie"},
    {"ticker": "FME.DE", "nom": "Fresenius Medical", "sector": "Santé"},
    {"ticker": "FRE.DE", "nom": "Fresenius SE", "sector": "Santé"},
    {"ticker": "HEI.DE", "nom": "Heidelberg Materials", "sector": "BTP"},
    {"ticker": "HEN3.DE", "nom": "Henkel", "sector": "Consommation"},
    {"ticker": "IFX.DE", "nom": "Infineon", "sector": "Technologie"},
    {"ticker": "MBG.DE", "nom": "Mercedes-Benz", "sector": "Automobile"},
    {"ticker": "MRK.DE", "nom": "Merck KGaA", "sector": "Santé"},
    {"ticker": "MTX.DE", "nom": "MTU Aero Engines", "sector": "Aéronautique"},
    {"ticker": "MUV2.DE", "nom": "Munich Re", "sector": "Assurance"},
    {"ticker": "P911.DE", "nom": "Porsche AG", "sector": "Automobile"},
    {"ticker": "PAH3.DE", "nom": "Porsche SE", "sector": "Holding"},
    {"ticker": "RHM.DE", "nom": "Rheinmetall", "sector": "Défense"},
    {"ticker": "RWE.DE", "nom": "RWE", "sector": "Énergie"},
    {"ticker": "SAP.DE", "nom": "SAP", "sector": "Technologie"},
    {"ticker": "SIE.DE", "nom": "Siemens", "sector": "Industrie"},
    {"ticker": "SHL.DE", "nom": "Siemens Healthineers", "sector": "Santé"},
    {"ticker": "SY1.DE", "nom": "Symrise", "sector": "Chimie"},
    {"ticker": "VOW3.DE", "nom": "Volkswagen", "sector": "Automobile"},
    {"ticker": "VNA.DE", "nom": "Vonovia", "sector": "Immobilier"},
    {"ticker": "ZAL.DE", "nom": "Zalando", "sector": "E-commerce"},
    {"ticker": "HFG.DE", "nom": "HelloFresh", "sector": "Consommation"},
    {"ticker": "LEG.DE", "nom": "LEG Immobilien", "sector": "Immobilier"},
    {"ticker": "QIA.DE", "nom": "Qiagen", "sector": "Santé"},
    {"ticker": "SDF.DE", "nom": "K+S", "sector": "Chimie"},

    # --- PAYS-BAS (AEX + AMX) ---
    {"ticker": "AD.AS", "nom": "Ahold Delhaize", "sector": "Distribution"},
    {"ticker": "AKZA.AS", "nom": "Akzo Nobel", "sector": "Chimie"},
    {"ticker": "ASML.AS", "nom": "ASML", "sector": "Technologie"},
    {"ticker": "ASM.AS", "nom": "ASM International", "sector": "Technologie"},
    {"ticker": "DSFIR.AS", "nom": "DSM-Firmenich", "sector": "Santé/Chimie"},
    {"ticker": "HEIA.AS", "nom": "Heineken", "sector": "Boisson"},
    {"ticker": "IMCD.AS", "nom": "IMCD", "sector": "Chimie"},
    {"ticker": "INGA.AS", "nom": "ING Group", "sector": "Banque"},
    {"ticker": "KPN.AS", "nom": "KPN", "sector": "Télécoms"},
    {"ticker": "NN.AS", "nom": "NN Group", "sector": "Assurance"},
    {"ticker": "PHIA.AS", "nom": "Philips", "sector": "Santé"},
    {"ticker": "PRX.AS", "nom": "Prosus", "sector": "Technologie"},
    {"ticker": "RELX.AS", "nom": "RELX", "sector": "Médias"},
    {"ticker": "UMG.AS", "nom": "Universal Music", "sector": "Médias"},
    {"ticker": "ADYEN.AS", "nom": "Adyen", "sector": "Finance Tech"},
    {"ticker": "BESI.AS", "nom": "BE Semiconductor", "sector": "Technologie"},

    # --- ITALIE (FTSE MIB) ---
    {"ticker": "A2A.MI", "nom": "A2A", "sector": "Énergie"},
    {"ticker": "AMP.MI", "nom": "Amplifon", "sector": "Santé"},
    {"ticker": "AZM.MI", "nom": "Azimut", "sector": "Finance"},
    {"ticker": "BAMI.MI", "nom": "Banco BPM", "sector": "Banque"},
    {"ticker": "BMED.MI", "nom": "Banca Mediolanum", "sector": "Banque"},
    {"ticker": "BPER.MI", "nom": "BPER Banca", "sector": "Banque"},
    {"ticker": "CPR.MI", "nom": "Campari", "sector": "Boisson"},
    {"ticker": "DIA.MI", "nom": "Diasorin", "sector": "Santé"},
    {"ticker": "ENEL.MI", "nom": "Enel", "sector": "Énergie"},
    {"ticker": "ENI.MI", "nom": "ENI", "sector": "Énergie"},
    {"ticker": "ERG.MI", "nom": "Erg", "sector": "Énergie"},
    {"ticker": "RACE.MI", "nom": "Ferrari", "sector": "Luxe"},
    {"ticker": "FBK.MI", "nom": "FinecoBank", "sector": "Banque"},
    {"ticker": "G.MI", "nom": "Generali", "sector": "Assurance"},
    {"ticker": "ISP.MI", "nom": "Intesa Sanpaolo", "sector": "Banque"},
    {"ticker": "INW.MI", "nom": "Infrastrutture Wireless", "sector": "Télécoms"},
    {"ticker": "ITM.MI", "nom": "Italgas", "sector": "Services"},
    {"ticker": "LDO.MI", "nom": "Leonardo", "sector": "Défense"},
    {"ticker": "MB.MI", "nom": "Mediobanca", "sector": "Banque"},
    {"ticker": "MONC.MI", "nom": "Moncler", "sector": "Luxe"},
    {"ticker": "PIRC.MI", "nom": "Pirelli", "sector": "Automobile"},
    {"ticker": "PST.MI", "nom": "Poste Italiane", "sector": "Finance"},
    {"ticker": "PRY.MI", "nom": "Prysmian", "sector": "Industrie"},
    {"ticker": "REC.MI", "nom": "Recordati", "sector": "Santé"},
    {"ticker": "SPM.MI", "nom": "Saipem", "sector": "Énergie"},
    {"ticker": "SRG.MI", "nom": "Snam", "sector": "Services"},
    {"ticker": "STMMI.MI", "nom": "STMicro Italy", "sector": "Technologie"},
    {"ticker": "TEN.MI", "nom": "Tenaris", "sector": "Énergie"},
    {"ticker": "TRN.MI", "nom": "Terna", "sector": "Services"},
    {"ticker": "UCG.MI", "nom": "Unicredit", "sector": "Banque"},
    {"ticker": "UNI.MI", "nom": "Unipol", "sector": "Assurance"},

    # --- ESPAGNE (IBEX 35) ---
    {"ticker": "ANA.MC", "nom": "Acciona", "sector": "BTP"},
    {"ticker": "ACS.MC", "nom": "ACS", "sector": "BTP"},
    {"ticker": "AMS.MC", "nom": "Amadeus", "sector": "Technologie"},
    {"ticker": "BBVA.MC", "nom": "BBVA", "sector": "Banque"},
    {"ticker": "CABK.MC", "nom": "Caixabank", "sector": "Banque"},
    {"ticker": "CLNX.MC", "nom": "Cellnex", "sector": "Télécoms"},
    {"ticker": "FER.MC", "nom": "Ferrovial", "sector": "Industrie"},
    {"ticker": "GRF.MC", "nom": "Grifols", "sector": "Santé"},
    {"ticker": "IBE.MC", "nom": "Iberdrola", "sector": "Énergie"},
    {"ticker": "ITX.MC", "nom": "Inditex", "sector": "Luxe/Retail"},
    {"ticker": "IDR.MC", "nom": "Indra Sistemas", "sector": "Technologie"},
    {"ticker": "MAP.MC", "nom": "Mapfre", "sector": "Assurance"},
    {"ticker": "MEL.MC", "nom": "Melia Hotels", "sector": "Hôtellerie"},
    {"ticker": "NTGY.MC", "nom": "Naturgy", "sector": "Énergie"},
    {"ticker": "RED.MC", "nom": "Redeia", "sector": "Services"},
    {"ticker": "REP.MC", "nom": "Repsol", "sector": "Énergie"},
    {"ticker": "SAN.MC", "nom": "Santander", "sector": "Banque"},
    {"ticker": "TEF.MC", "nom": "Telefonica", "sector": "Télécoms"},

    # --- BELGIQUE & LUXEMBOURG ---
    {"ticker": "ABI.BR", "nom": "AB InBev", "sector": "Consommation"},
    {"ticker": "ACKB.BR", "nom": "Ackermans", "sector": "Holding"},
    {"ticker": "AGEAS.BR", "nom": "Ageas", "sector": "Assurance"},
    {"ticker": "ARGX.BR", "nom": "Argenx", "sector": "Santé"},
    {"ticker": "GBLB.BR", "nom": "GBL", "sector": "Holding"},
    {"ticker": "KBC.BR", "nom": "KBC Group", "sector": "Banque"},
    {"ticker": "SOLB.BR", "nom": "Solvay", "sector": "Chimie"},
    {"ticker": "SYENS.BR", "nom": "Syensqo", "sector": "Chimie"},
    {"ticker": "UCB.BR", "nom": "UCB", "sector": "Santé"},
    {"ticker": "UMI.BR", "nom": "Umicore", "sector": "Chimie"},
    {"ticker": "WDP.BR", "nom": "WDP", "sector": "Immobilier"},

    # --- FINLANDE & SCANDINAVIE (ZONE UE) ---
    {"ticker": "ELISA.HE", "nom": "Elisa", "sector": "Télécoms"},
    {"ticker": "FORTUM.HE", "nom": "Fortum", "sector": "Énergie"},
    {"ticker": "KNEBV.HE", "nom": "Kone", "sector": "Industrie"},
    {"ticker": "METSA.HE", "nom": "Metsä Board", "sector": "Industrie"},
    {"ticker": "NESTE.HE", "nom": "Neste", "sector": "Énergie"},
    {"ticker": "NOKIA.HE", "nom": "Nokia", "sector": "Technologie"},
    {"ticker": "ORNBV.HE", "nom": "Orion", "sector": "Santé"},
    {"ticker": "SAMPO.HE", "nom": "Sampo", "sector": "Finance"},
    {"ticker": "STERV.HE", "nom": "Stora Enso", "sector": "Industrie"},
    {"ticker": "UPM.HE", "nom": "UPM-Kymmene", "sector": "Industrie"},
    {"ticker": "WRT1V.HE", "nom": "Wärtsilä", "sector": "Industrie"},
    {"ticker": "ASSA-B.ST", "nom": "Assa Abloy", "sector": "Industrie"},
    {"ticker": "ATCO-A.ST", "nom": "Atlas Copco", "sector": "Industrie"},
    {"ticker": "ERIC-B.ST", "nom": "Ericsson", "sector": "Technologie"},
    {"ticker": "ESSITY-B.ST", "nom": "Essity", "sector": "Santé"},
    {"ticker": "EPI-B.ST", "nom": "Epiroc", "sector": "Industrie"},
    {"ticker": "HM-B.ST", "nom": "H&M", "sector": "Retail"},
    {"ticker": "INDU-C.ST", "nom": "Industrivärden", "sector": "Holding"},
    {"ticker": "INVE-B.ST", "nom": "Investor AB", "sector": "Holding"},
    {"ticker": "SAND.ST", "nom": "Sandvik", "sector": "Industrie"},
    {"ticker": "SKF-B.ST", "nom": "SKF", "sector": "Industrie"},
    {"ticker": "SWED-A.ST", "nom": "Swedbank", "sector": "Banque"},
    {"ticker": "TELIA.ST", "nom": "Telia", "sector": "Télécoms"},
    {"ticker": "VOLV-B.ST", "nom": "Volvo Group", "sector": "Industrie"},
    {"ticker": "NOVO-B.CO", "nom": "Novo Nordisk", "sector": "Santé"},
    {"ticker": "DSV.CO", "nom": "DSV", "sector": "Logistique"},
    {"ticker": "ORSTED.CO", "nom": "Orsted", "sector": "Énergie"},
    {"ticker": "MAERSK-B.CO", "nom": "Maersk", "sector": "Transport"},
    {"ticker": "CARL-B.CO", "nom": "Carlsberg", "sector": "Boisson"},

    # --- AUTRES EU (PORTUGAL, AUTRICHE) ---
    {"ticker": "EDP.LS", "nom": "EDP", "sector": "Énergie"},
    {"ticker": "GALP.LS", "nom": "Galp Energia", "sector": "Énergie"},
    {"ticker": "JMT.LS", "nom": "Jerónimo Martins", "sector": "Distribution"},
    {"ticker": "EBS.VI", "nom": "Erste Group", "sector": "Banque"},
    {"ticker": "OMV.VI", "nom": "OMV", "sector": "Énergie"},
    {"ticker": "VER.VI", "nom": "Verbund", "sector": "Énergie"}
]
