name: Scan Bourse Automatique

on:
  schedule:
    # Se lance toutes les heures de 9h à 18h (UTC), du lundi au vendredi
    - cron: name: Scan Bourse Automatique

on:
  schedule:
    # Se lance toutes les heures de 9h à 18h (UTC), du lundi au vendredi
    - cron: '*/15 8-17 * * 1-5' 
  workflow_dispatch: # Permet de le lancer manuellement pour tester

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v2

      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt

      - name: Lancer le Scan
        run: python worker.py 
  workflow_dispatch: # Permet de le lancer manuellement pour tester

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v2

      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt

      - name: Lancer le Scan
        run: python worker.py
